Topic 05 - Packages
ericrommel/python_test_automation_book pull request #28
Opened 2024-11-16 10:14 UTC by ksauhen

2024-11-16 19:19 UTC, SSN-SPB requested changes

2024-11-16 19:19 UTC, SSN-SPB commented on topics/05_module_packages_and_testing_frameworks/packages.md
I am very confused with structure of file.
It doesn't explain package/module/subpackage

1st line 
During test automation framework development, you will create many modules and it will be difficult to maintain them if they are all placed in one location.

3d
### Example:

Example of what?

What about starting with explanation:
What is package
If module is subject of this topic - explain it here as well.
Explain the difference (advantage/disadvantage of using) package/module/subpackage

The next:
"## 2.2 Initializing Package

If a file named `__init__.py` is present in a package directory"

The __init__.py is mentioned in this text first time. imho it is need to explain what is role of __init__.py file

2024-11-17 11:23 UTC, ksauhen commented on topics/05_module_packages_and_testing_frameworks/packages.md
Please be aware that the PR covers only packages. __init__.py is mentioned in Initializing Package for the first time, because this section explains it

2024-11-21 19:26 UTC, SSN-SPB approved these changes
imho it is good for lecture.

2024-11-22 09:21 UTC, merged