05 testing frameworks
ericrommel/python_test_automation_book pull request #29
Opened 2024-11-27 22:25 UTC by ksauhen

2024-11-29 11:24 UTC, ericrommel requested changes

2024-11-29 17:21 UTC, ksauhen commented on topics/05_module_packages_and_testing_frameworks/testing_frameworks.md
> +def get_request(self, url, headers, params):
Updated

2024-11-30 11:34 UTC, ericrommel requested changes

2024-11-30 11:34 UTC, ericrommel commented on topics/05_module_packages_and_testing_frameworks/testing_frameworks.md
> +I hope this helps! Let me know if you need more information or have any other questions.
I think this text was missed here

2024-12-02 09:14 UTC, ericrommel approved these changes

2024-12-02 09:54 UTC, merged